### ISSUE TITLE
Always Encrypted Roadmap

### ISSUE THREAD

**Issue by arthurschreiber** [tediousjs/tedious#1584]
- [ ] Extend `FeatureExtAckToken` parser to support `COLUMNENCRYPTION` token id (see https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/2eb82f8e-11f0-46dc-b42d-27302fa4701a)
- [ ] Extend `ColMetadataToken` parser to be able to read `CryptoMetaData` information (see https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/58880b9f-381c-43b2-bf8b-0727a98c4f4c)
- [ ] Extend `Login7Payload` to allow signalling to the server that `tedious` supports encryption (see https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/773a62b6-ee89-4c02-9e5e-344882630aac)
- [ ] ...
